name: Create Subdomain DNS Record

on:
  pull_request:
    types: [closed] # Trigger when a pull request is closed
    branches:
      - main # Or your default branch (e.g., 'master')

jobs:
  create-dns:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Only run if the PR was merged, not just closed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Get merged file path
        # This step figures out which JSON file was merged.
        # It's a bit tricky to get *only* the merged file path reliably in GitHub Actions.
        # A simpler approach for *this specific use case* might be to assume the PR
        # only contains one JSON file addition.
        # For more robust solutions, consider:
        # - Looping through changes to find added files
        # - Having a specific naming convention
        # For now, let's assume one file added, and it's named like the subdomain.
        id: get_file_path
        run: |
          # This assumes a clean merge with only one new JSON file added to 'domains/'
          # You might need to refine this for complex PRs.
          NEW_FILE=$(git diff --name-only ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} | grep 'domains/.*\.json' | head -n 1)
          if [ -z "$NEW_FILE" ]; then
            echo "::error::No new JSON file found in 'domains/' directory for this PR."
            exit 1
          fi
          echo "NEW_FILE_PATH=$NEW_FILE" >> $GITHUB_OUTPUT
          echo "Discovered new file: $NEW_FILE"

      - name: Run DNS creation script
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }} # You need to set this in GitHub Secrets too!
        run: python scripts/add_dns_record.py ${{ steps.get_file_path.outputs.NEW_FILE_PATH }}
