name: '[Debug] Secret Availability Test'

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  verify-secrets:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check for presence of secrets
        run: |
          echo "Attempting to verify secrets..."
          if [ -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" ] && [ -n "${{ secrets.CLOUDFLARE_ZONE_ID }}" ]; then
            echo "✅ SUCCESS: Both secrets are available and not empty."
            exit 0
          else
            echo "❌ FAILURE: One or both secrets are MISSING or EMPTY."
            
            # This is a safe way to check if they exist without printing them
            if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
              echo "   - CLOUDFLARE_API_TOKEN is NOT SET."
            else
              echo "   - CLOUDFLARE_API_TOKEN is set (but might be empty)."
            fi

            if [ -z "${{ secrets.CLOUDFLARE_ZONE_ID }}" ]; then
              echo "   - CLOUDFLARE_ZONE_ID is NOT SET."
            else
              echo "   - CLOUDFLARE_ZONE_ID is set (but might be empty)."
            fi
            
            exit 1
          fi
